export enum MyGeneration {
  FIRST_GENERATION = "FIRST_GENERATION" ,
  SECOND_GENERATION = "SECOND_GENERATION" ,
  THIRD_GENERATION = "THIRD_GENERATION" ,
  FOURTH_GENERATION = "FOURTH_GENERATION" ,
  FIFTH_GENERATION = "FIFTH_GENERATION" ,
  SIXTH_GENERATION = "SIXTH_GENERATION" ,
  SEVENTH_GENERATION = "SEVENTH_GENERATION" ,
  EIGHTH_GENERATION = "EIGHTH_GENERATION" ,
  NINTH_GENERATION = "NINTH_GENERATION" ,
  TENTH_GENERATION = "TENTH_GENERATION"
}
